# Generated by Django 3.2.4 on 2021-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.JSONField(blank=True),
        ),
    ]
